spring:
  application:
    name: ingest-service
  
  server:
    port: 8081
    
  redis:
    host: localhost
    port: 6379

binance:
  ws:
    base-url: wss://stream.binance.com:9443/stream

ingest:
  redis-channel-prefix: candles
  max-candles-cache: 500
