spring:
  application:
    name: ingest-service

  data:
    redis:
      host:  localhost
      port: 6379
      password: redis123
      timeout: 2000ms
server:
  port: 8081

binance:
  ws:
    base-url: wss://stream.binance.com:9443/stream
  rest:
    base-url: https://api.binance.com/api/v3

ingest:
  redis-channel-prefix: candles
  max-candles-cache: 500

storage-service:
  url: http://localhost:8082

logging:
  level:
    com.example. ingest: INFO
    io.lettuce. core: DEBUG