spring:
  application:
    name: ingest-service

  data:
    redis:
      host:  localhost
      port: 6379
      password: redis123
      timeout: 2000ms
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

      retries: 3
      batch-size: 65536
      linger-ms: 5
      buffer-memory: 33554432

      compression-type: lz4

server:
  port: 8081

binance:
  ws:
    base-url: wss://stream.binance.com:9443/stream
  rest:
    base-url: https://api.binance.com/api/v3

ingest:
  redis-channel-prefix: candles
  max-candles-cache: 500

storage-service:
  base-url: http://localhost:8082

logging:
  level:
    com.example.ingest: INFO
kafka:
  topics:
    closed-candles: closed-candles
